services:
  nginx:
    container_name: "nginx"
    build:
      # nginx directory를 root로 사용
      context: ./nginx
      # ./nginx/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "20080:80"
    depends_on:
      - quil
      - ysocket
  quil:
    container_name: "quil"
    build:
      # velog directory를 root로 사용
      context: ./quil
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
  ysocket:
    container_name: "ysocket"
    build:
      # velog directory를 root로 사용
      context: ./ysocket
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile